export enum NotificationType {
  COMMENT_ON_PUBLICATION = 'COMMENT_ON_PUBLICATION',
  RESPONSE_TO_COMMENT = 'RESPONSE_TO_COMMENT',
  RESPONSE_TO_RESPONSE = 'RESPONSE_TO_RESPONSE',
  LIKE_PUBLICATION = 'LIKE_PUBLICATION',
  NEW_MESSAGE = 'NEW_MESSAGE',
  MESSAGE_EDITED = 'MESSAGE_EDITED',
  MESSAGE_DELETED = 'MESSAGE_DELETED',
  MESSAGE_LIKED = 'MESSAGE_LIKED',

  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_MESSAGE = 'GROUP_MESSAGE',
  GROUP_MEMBER_ADDED = 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED = 'GROUP_MEMBER_REMOVED',
  GROUP_EDITED = 'GROUP_EDITED',
  GROUP_DELETED = 'GROUP_DELETED',
  GROUP_MESSAGE_EDITED = 'GROUP_MESSAGE_EDITED',
  GROUP_MESSAGE_DELETED = 'GROUP_MESSAGE_DELETED',
  YOURSELF_GROUP_MEMBER_REMOVED = 'YOURSELF_GROUP_MEMBER_REMOVED',

  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_EDITED = 'EVENT_EDITED',
  EVENT_DELETED = 'EVENT_DELETED',

  PUBLICATION_CREATED = 'PUBLICATION_CREATED',
}
