version: '3'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: EcoSwap-DB
